version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - ../.env
    volumes:
      - engineering-blogs:/var/lib/postgresql/data

volumes:
  engineering-blogs:
